createInstaller:
    tags:
        - rad-io2
    stage: build
    script:
        - yarn dist
    artifacts:
        name: "%CI_JOB_NAME%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHA%"
        paths:
            - updater/neoRAD-IO2-Updater.exe
            - dist/neoRAD-IO2 Setup 1.6.4.exe
        expire_in: 1 month