const english = {
    menu_main:"Menu",
    menu_about:"About",
    menu_settings:"Settings",
    menu_exit:"Quit",
    menu_view:"View",
    menu_view_device:"Devices",
    menu_view_graph:"Graph",
    menu_view_help:"Help",
    menu_reload:"Reload",
    menu_advanced:"Advanced",
    menu_calibration:"Show Calibration",
    menu_folder:"Open Data Folder",
    calibration:"Calibration",
    reload_message:"Are you sure you want to restart? \nAll UNSAVED DATA WILL BE LOST !!",
    reload_ok:"Confirm",
    reload_cancel:"Cancel",
    not_available:"Not available",
    cal_warning:"Warning, calibration settings is a one off feature that will set your device only once, if you use the wrong settings you will need to send your device back for recalibration",
    cal_toggle_show:"Are you sure you want to\nSHOW\nCalibration feature?",
    cal_toggle_hide:"Are you sure you want to\nHIDE\nCalibration feature?",
    cal_leave:"All unsaved data will be lost when you leave Calibration!!",
    quit:"Are you sure you want to quit?"
};

const japanese = {
    menu_main:"メニュー",
    menu_about:"About",
    menu_settings:"設定",
    menu_exit:"閉じる",
    menu_view:"表示",
    menu_view_device:"デバイス",
    menu_view_graph:"グラフ",
    menu_view_help:"ヘルプ",
    menu_reload:"リロード",
    menu_advanced:"アドバンスド",
    menu_calibration:"較正",
    menu_folder:"Open Data Folder",
    calibration:"較正",
    reload_message:"再起動してもよろしいですか？\nすべてのデータを失われる！！",
    reload_ok:"確認",
    reload_cancel:"キャンセル",
    not_available:"利用不可",
    cal_warning:"Warning, calibration settings is a one off feature that will set your device only once, if you use the wrong settings you will need to send your device back for recalibration",
    cal_leave:"All unsaved data will be lost when you leave Calibration!!",
    quit:"Are you sure you want to quit?"
};

const korean = {
    menu_main: "메뉴",
    menu_about:"정보",
    menu_settings: "설정",
    menu_exit: "종료",
    menu_view: "보기",
    menu_view_device: "장비",
    menu_view_graph:"그래프",
    menu_view_help: "도움말",
    menu_reload: "재시작",
    menu_advanced: "고급",
    menu_calibration: "캘리브레이션 표시",
    menu_folder:"데이터 폴더 열기",
    calibration: "캘리브레이션",
    reload_message: "재시작하시겠습니까? \n저장하지 않은 데이터는 손실됩니다!!",
    reload_ok: "확인",
    reload_cancel: "취소",
    not_available:"불가능",
    cal_warning: "경고, 캘리브레이션 설정은 한 번만 가능합니다. 잘못 설정하신 경우에는 장비를 반납하셔야합니다.",
    cal_toggle_show: "캘리브레이션 메뉴를 표시하시겠습니까?",
    cal_toggle_hide: "캘리브레이션 메뉴를 숨기시겠습니까?",
    cal_leave: "저장하지 않은 데이터는 캘리브레이션 종료시 손실됩니다!!",
    quit:"종료하시겠습니까?"
};

const chinese = {
    menu_main:"菜单",
    menu_about:"关于",
    menu_settings:"设置",
    menu_exit:"退出",
    menu_view:"查看",
    menu_view_device:"设备列表",
    menu_view_graph:"数据图表",
    menu_view_help:"帮助",
    menu_reload:"重载",
    menu_advanced:"高级",
    menu_calibration:"显示校准",
    menu_folder:"打开数据文件目录",
    calibration:"标定",
    reload_message:"确定是否要重新加载？\n所有未保存的记录都会丢失！！",
    reload_ok:"确认",
    reload_cancel:"取消",
    not_available:"无法使用",
    cal_warning:"警告, 校准设置只能进行一次，如果设置错误需要寄回设备重置标定数据",
    cal_toggle_show:"是否确定\n显示\n标定功能?",
    cal_toggle_hide:"是否确定\n隐藏\n标定功能?",
    cal_leave:"确定是否要离开？所有未保存数据都将丢失!!",
    quit:"确认是否要退出?"
};

const Tchinese = {
    menu_main:"菜單",
    menu_about:"關於",
    menu_settings:"設置",
    menu_exit:"退出",
    menu_view:"查看",
    menu_view_device:"設備列表",
    menu_view_graph:"數據圖表",
    menu_view_help:"幫助",
    menu_reload:"重載",
    menu_advanced:"高級",
    menu_calibration:"顯示標定",
    menu_folder:"打開數據文件目錄",
    calibration:"標定",
    reload_message:"確定是否要重新加載？\n所有未保存的記錄都會丟失！！",
    reload_ok:"確認",
    reload_cancel:"取消",
    not_available:"無法使用",
    cal_warning:"警告, 校准设置只能进行一次，如果设置错误需要寄回设备重置校准数据",
    cal_toggle_show:"是否確定\n顯示\n標定功能?",
    cal_toggle_hide:"是否確定\n隱藏\n標定功能?",
    cal_leave:"確定是否要離開？所有未保存數據都將丟失!!",
    quit:"确认是否要退出?"
};

const locale = {
    "en": english,
    "ja": japanese,
    "jw": japanese,
    "ko": korean,
    "zh": chinese,
    "zh-CN": chinese,
    "zh-TW": Tchinese
};

module.exports = locale;